  <font size="5">
 <div class="alert alert-block alert-info"> <b>Módulo introdutório de Python - Aula 3<b>
     </div>
</font> 
 
 \vspace{.1in}
     
    
  <font size="4"> Mestrado em Ciência de Dados </font>
  \vspace{.03in}
  
  
  <font size="3"> **Diana Aldea Mendes** </font>
     \vspace{.02in}
  <font size="3">ISCTE-IUL, 5-9 de setembro de 2023 </font>
  \vspace{.03in}
  
   
  <font size="3"> *diana.mendes@iscte-iul.pt* </font> 
  \vspace{.03in}



<font size="5"> 
    <div class="alert alert-warning" role="alert"> Today topics </div> </font> 
  \vspace{.03in}
  
 - **Numpy**
    * Installing and importing NumPy
    * Numpy ndarray
    * Creation routines
    * Random
    * Reshape
    * Operations
    * Indexing and Selection
    * Boolean Indexing
    * Concatenation and splitting
    * Universal Array Functions
    * Load and Save to file
 

<div class="alert alert-block alert-info">
<font size="4"> <b>Bibliografia <b>  </font> 
    </div>
 
 \vspace{.04in}
    
(1) Wes McKinney (2022), Python for Data Analysis, Third Edition, O’Reilly Media, Inc. 
(book and code: https://wesmckinney.com/book/, https://github.com/wesm/pydata-book/) 

(2) Python Documentation (https://docs.python.org/3/)    

(3) Jake VanderPlas (2016), Python Data Science Handbook, O’Reilly Media, Inc. (disponível em https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb) 

(4) Matt Harrison and Theodore Petrou (2020), Pandas 1.x Cookbook, Second Edition, Packt>.
(https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition)


#  Numpy 


- **NumPy** is the fundamental package for scientific computing with Python. 
- It contains among other things: a powerful N-dimensional array object, functions and routines, tools for integrating C/C++ and Fortran code, useful linear algebra, Fourier transform, and random number capabilities.
- https://numpy.org/

- Base data structure in numpy: **array**
- Note that, the elements of an array can be:
    - integer numbers, 
    - real numbers (float type), 
    - strings ('ABC', 'Nuno', 'lisboa'),
    - boolean (True, False),
    - mixed elements (for example: numbers and strings)
    - date objects
    
- Each array has attributes 
    - ``ndim`` (the number of dimensions),
    - ``shape`` (the size of each dimension), and 
    - ``size`` (the total size of the array = sum of all entries in the array)



## Installing and Importing
To install:

`conda install numpy`

or

`pip install numpy`

In [1]:
# call the package/library with 'import'
# we have to mention the package name when we call modules and functions from numpy
# we will associate a short and easy calling name to the package - canonical name or alias.
# usually this short name is 'np'

import numpy as np

## One-dimensional arrays

In [2]:
# Arrays can be "n"-dimensional --but most commonly one, two or three dimensional
# we define a 1-dimensional array (vector/list) with numpy 'np' and buil-in function 'array'

a_list = [2,3,4]
a = np.array(a_list)
a


array([2, 3, 4])

In [3]:
# the same
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [5]:
### Array or list ???? Which are the differences???
# visualize the 1-dim array a
# visualize the list a_list
print(a)

print(a_list)

[2 3 4]
[2, 3, 4]


**Diferenças entre lista e array**

List | Array
-----|-------
Contains elements of different data types. | Contains elements of the same data types.
Explicitly importing modules is not required to declare a list. | Need to import the module explicitly to declare an array.
Cannot handle arithmetic operations. | Can handle arithmetic operations.
Can be nested inside another list. | Must contain all elements of the same size.
Mostly used in the shorter sequence of data elements. | Mostly used in the longer sequence of data elements.
Easy modifications like addition, deletion, and update of data elements are done. | It is difficult to modify an array since addition, deletion, and update operation is performed on a single element at a time.
We can print the entire list without the help of an explicit loop. | To print or access array elements, we will require an explicit loop.
For easy addition of elements, large memory storage is required. | In comparison to the list, it is more compact in-memory size.

In [6]:
# type of elements (entries) in the array 'a'
a.dtype

dtype('int32')

In [7]:
# shape of the array
a.shape

(3,)

In [8]:
# dimension of the array
a.ndim

1

In [9]:
# max and min value of array a
a.max(), a.min()

(4, 2)

In [10]:
# média, soma, soma cumulativa
a.mean(), a.sum(), a.cumsum()

(3.0, 9, array([2, 5, 9]))

########################################################################

- Only one type of elements it is permited in an array
- When there are several types, Python/Numpy will project all elements to the most general type (cast, casting)


- Num array só pode existir um tipo de elementos !!!!
- Em caso de conflitos de tipo, o ambiente vai fazer uma projeção para um tipo conhecido ('cast') - o mais geral possível.


In [11]:
np.array([1,2,"a", 3])
# we have integer numbers and a string - will atualize all elements to strings

array(['1', '2', 'a', '3'], dtype='<U11')

In [12]:
np.array([1.2,1,2,3])
# actualize integer and float to float

array([1.2, 1. , 2. , 3. ])

## Multidimensional Arrays

In [13]:
# define a matrix (of type (2x3) - 2 lines and 3 columns) or a 2-dim array 
# each line elements are inside (), two lines are separated by ','

# array dimensão 1 - só um parenteses reto
# array dimensão 2 - tem dois parenteses retos

b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [14]:
# shape of the array
b.shape

(2, 3)

In [15]:
b.ndim

2

In [20]:
# A unitary 3-dimensional array (in this case of type (2x3x4)) can be defined with 'np.ones'
ones_array = np.ones((2, 3, 4), dtype=float)

# 2 - duas matrizes
# 3 - cada matriz com três linhas
# 4 - cada matriz tem 4 colunas

print(ones_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [17]:
ones_array.ndim

3

In [21]:
# Eye matrix (kind of Identity matrix from linear algebra - but can be defined for any order)
I = np.eye(3,5)

print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Creation routines

- Several form to define arrays with built-in functions

- `arrange(a,b,c)`
    - first index - a: start of sequence
    - second index - b: end of sequence, exclusive
    - third index - c: step
- `linspace(k, l, m)`
    - first index - k: start of sequence
    - second index - l: end of sequence, exclusive
    - third index - m: number of elements in the sequence

In [22]:
# use np.arrange to define an array

np.arange(10, 330, 5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200,
       205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265,
       270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325])

In [23]:
# in 'linspace' function, specify number of elements instead of step-size

np.linspace(0, 9, 88)

array([0.        , 0.10344828, 0.20689655, 0.31034483, 0.4137931 ,
       0.51724138, 0.62068966, 0.72413793, 0.82758621, 0.93103448,
       1.03448276, 1.13793103, 1.24137931, 1.34482759, 1.44827586,
       1.55172414, 1.65517241, 1.75862069, 1.86206897, 1.96551724,
       2.06896552, 2.17241379, 2.27586207, 2.37931034, 2.48275862,
       2.5862069 , 2.68965517, 2.79310345, 2.89655172, 3.        ,
       3.10344828, 3.20689655, 3.31034483, 3.4137931 , 3.51724138,
       3.62068966, 3.72413793, 3.82758621, 3.93103448, 4.03448276,
       4.13793103, 4.24137931, 4.34482759, 4.44827586, 4.55172414,
       4.65517241, 4.75862069, 4.86206897, 4.96551724, 5.06896552,
       5.17241379, 5.27586207, 5.37931034, 5.48275862, 5.5862069 ,
       5.68965517, 5.79310345, 5.89655172, 6.        , 6.10344828,
       6.20689655, 6.31034483, 6.4137931 , 6.51724138, 6.62068966,
       6.72413793, 6.82758621, 6.93103448, 7.03448276, 7.13793103,
       7.24137931, 7.34482759, 7.44827586, 7.55172414, 7.65517

In [24]:
# Empty array

emptyArray = np.empty((3,2))

print(emptyArray)

[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]


In [26]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in

In [27]:
# Example: define an array by using range function

# a função range exclui o último elemento

np.array([range(i, i + 2) for i in [1,3,5,7]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

In [31]:
# null matrix or null two-dimensional array, all entries are zero
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
## the same as before, but with integer entries
np.zeros((2,3,4), dtype='int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [33]:
## diagonal matrix
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Example

In [ ]:
L = range(1000)
%timeit [i**2 for i in L] # calcula o tempo de execução, % - magic

In [35]:
a = np.arange(1000)
%timeit a**2

8.07 µs ± 1.3 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Operations with arrays

In [38]:
# simple operations with arrays

a = np.array([5, 6, 7, 8])
b = np.arange(4, 20, 4)
print('a =', a)
print('b =', b)


a = [5 6 7 8]
b = [ 4  8 12 16]


In [41]:
# sum or difference - opera sobre elementos homólogos, ou seja, na mesma  posição em cada um dos arrays
print('sum =', a + b)

print('dif = ', a - b)

sum = [ 9 14 19 24]
dif =  [ 1 -2 -5 -8]


In [42]:
# multiply each entry by a number
print(2 * b)

[ 8 16 24 32]


In [43]:
print(10 * np.sin(a))

[-9.58924275 -2.79415498  6.56986599  9.89358247]


## Random numbers and Reshape function

In [44]:
# Create uniform random variable 'x' (1-dim array)

x = np.random.uniform(1, 10, 20)

x

array([8.04553131, 2.611577  , 1.34879741, 1.26786833, 6.45929886,
       1.76315507, 4.82866824, 2.53439151, 3.5592521 , 2.80239295,
       6.1075906 , 8.48323554, 5.45790925, 7.91959786, 8.6988291 ,
       9.4032774 , 8.87806673, 4.28435571, 1.52057633, 7.70575957])

In [46]:
# random integer entries, values between 1 and 100, 2-dim array
# np - nome da biblioteca
# random - módulo
# randint - função

y = np.random.randint(1,100,(5,3))

y

array([[10,  4, 59],
       [99, 29, 19],
       [14, 41, 56],
       [99, 56,  9],
       [35, 88, 22]])

In [47]:
import numpy.random as npr
# To isolate the randomness for sensitivity analysis (or for reproducibility) use a seed value
# run several times and observe the variables c and d

for i in range(0,7):
    c = npr.randint(20, size=10)
    print("c=", i, "=", c)
    
print('\n')



c= 0 = [17  7  8 10  7  0  2 17  6  6]
c= 1 = [ 4  4  0  9 18  9 19 13  8 14]
c= 2 = [13 14 12  2  9  6 19  3  0 10]
c= 3 = [ 0 11 14 17 18 15 14  5  4  9]
c= 4 = [12 15  3  9 14 14 11 15  9  6]
c= 5 = [ 5  9  3  6 19 11  1  7  8 17]
c= 6 = [10  2  9  6 12  4 17 14 12 13]




In [48]:

for i in range(0,7):
    npr.seed(42)
    d = npr.randint(20, size=10)
    print("d=", i, "=", d)

d= 0 = [ 6 19 14 10  7  6 18 10 10  3]
d= 1 = [ 6 19 14 10  7  6 18 10 10  3]
d= 2 = [ 6 19 14 10  7  6 18 10 10  3]
d= 3 = [ 6 19 14 10  7  6 18 10 10  3]
d= 4 = [ 6 19 14 10  7  6 18 10 10  3]
d= 5 = [ 6 19 14 10  7  6 18 10 10  3]
d= 6 = [ 6 19 14 10  7  6 18 10 10  3]


### Reshape

In [56]:
# reshape an array (from 1-dim array of type (1x15) to 2-dim array of type (3x5))
data = npr.randint(10, size=15)
print("data=", data)

data_1 = data.reshape(3,5)
print("data_1=", data_1)

data= [6 3 8 2 4 2 6 4 8 6 1 3 8 1 9]
data_1= [[6 3 8 2 4]
 [2 6 4 8 6]
 [1 3 8 1 9]]


In [50]:
arr5 = np.random.randint(100,size=(3,4))
arr5

array([[90, 58, 41, 91],
       [59, 79, 14, 61],
       [61, 46, 61, 50]])

In [51]:
arr5.shape

(3, 4)

In [52]:
arr5.reshape(-1)

array([90, 58, 41, 91, 59, 79, 14, 61, 61, 46, 61, 50])

In [53]:
arr5.reshape(4,3)

array([[90, 58, 41],
       [91, 59, 79],
       [14, 61, 61],
       [46, 61, 50]])

In [54]:
arr5.reshape(2,6)

array([[90, 58, 41, 91, 59, 79],
       [14, 61, 61, 46, 61, 50]])

In [55]:
arr5.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

#### Review Example

In [60]:
x3 = np.array([(1,-1),('abc','www'),(2.34,0.55),(0,True)])
print('x3=', x3)
print("x3 ndim: ", x3.ndim) # dimensão 2, basta contar os parênteses que abrem
print("x3 shape:", x3.shape) # número de linhas x colunas
print("x3 size: ", x3.size) # número de elementos
print("dtype:", x3.dtype)  
print('reshaped_array=', x3.reshape(2,4))

x3[1][0] # índice [1] - linha, índice [0] - coluna |> 'abc'

x3= [['1' '-1']
 ['abc' 'www']
 ['2.34' '0.55']
 ['0' 'True']]
x3 ndim:  2
x3 shape: (4, 2)
x3 size:  8
dtype: <U32
reshaped_array= [['1' '-1' 'abc' 'www']
 ['2.34' '0.55' '0' 'True']]


'abc'

## Indexing and slicing

#################################################################################

**Array Indexing**: Accessing Single Elements and Sub-arrays (Similar to list indexing).

**Indexing in NumPy** : in a one-dimensional array, the  𝑖-𝑡ℎ  value (counting from **zero**) can be accessed by specifying the desired index in **square brackets**!

- ``a[n], a[-n]`` - forward and backward indexing
-  ``x[start:stop:step]`` - slicing

In [58]:
# define an 1-dim array
a = np.linspace(3, 36, 12)
a

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36.])

In [61]:
# first element of 'a' (of index 0) (from the left)
a[0]

3.0

In [62]:
# the second element backward (counting from the end)
a[-2]

33.0

In [63]:
# range chosen [2, 5) (do not include element of index 5)
a[2:5]

array([ 9., 12., 15.])

In [64]:
# every second element from zero to index 6
a[:6:2]  

array([ 3.,  9., 15.])

In [65]:
# reverse array a
bai = a[::-1]

bai

array([36., 33., 30., 27., 24., 21., 18., 15., 12.,  9.,  6.,  3.])

In [66]:
# another example
x = np.arange(10)
x
x[:5]  # first five elements
x[5:]  # elements after index 5
x[4:7]  # middle sub-array
x[::2]  # every other element
x[1::2]  # every other element, starting at index 1
x[::-1]  # all elements, reversed
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

###################################################################################

- In a multi-dimensional array, items can be accessed using a **comma-separated tuple of indices**: `x[n,m]`

In [3]:
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [6]:
# isolate element from line 3 and column 1, which means with index 2 and 0
x2[0:3, 0:2]

array([[5, 0],
       [7, 9],
       [2, 4]])

In [14]:
# last element from line 3 (line 3 has index 2)
# x2[índice posição linha, índice posição coluna]
x2[2,-1], x2[:, 0]

(6, array([5, 7, 2]))

In [70]:
# Values can also be modified using any of the above index notation:
# substitute the first element (value '5') by a new element of value '12'
x2[0, 0] = 12
x2

array([[12,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

### Accessing array rows and columns**

- One commonly needed routine is accessing of *single rows or columns* of an array.

- This can be done by combining **indexing and slicing**, using an empty slice marked by a single colon (``:``):

In [15]:
# extract (2x2) subarray
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 0]
 [7 9]]


In [16]:
x2[:2, :3]  # two rows, three columns


array([[5, 0, 3],
       [7, 9, 3]])

In [17]:
x2[:3, ::2]  # all rows, every other column


array([[5, 3],
       [7, 3],
       [2, 7]])

In [18]:
# invert elements position in the 2-dim array x2
x2[::-1, ::-1]

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]])

### Boolean Indexing

In [19]:
names = np.array(["Maria", "James", "Sarah", "Peter"])

grades = np.array([4,15,11,9])

In [26]:
positive = grades > 10
positive

array([False,  True,  True, False])

In [21]:
grades[names != "Maria"]

array([15, 11,  9])

 ###############################################################################
 
## Concatenation, stacking and splitting 

- **Concatenation**, or **joining** of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``

- ``np.concatenate`` takes a tuple or list of arrays as its first argument.

- We can **stack** 2 arrays vertically and horizontaly by using the buil-in functions: ``np.vstack`` and ``np.hstack``.
    
    

- The opposite of concatenation is **splitting**, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  



In [30]:
x3 = np.array([1, 2, 3, 99, 99, 3, 2, 1])
y3 = np.array([2, -2, 1, 0, 8, 1, 5, 7])

# join/concatenate the elements of the 2 arrays (x3 and y3)
z3 = np.concatenate((x3, y3), axis=0)

print("z3 =", z3)


z3 = [ 1  2  3 99 99  3  2  1  2 -2  1  0  8  1  5  7]


In [27]:
arr_a = np.arange(0,4)
arr_b = np.arange(-4,0)
arr_a, arr_b

(array([0, 1, 2, 3]), array([-4, -3, -2, -1]))

In [28]:
# sobrepor verticalmente

np.vstack((arr_a,arr_b))

array([[ 0,  1,  2,  3],
       [-4, -3, -2, -1]])

In [29]:
np.hstack((arr_a,arr_b))

array([ 0,  1,  2,  3, -4, -3, -2, -1])

In [34]:
x = np.array([[1, 2, 3, 99], [3, 2, 1, 3]])

print('x =', x)

# split x into 3 sub-arrays
x1, x2 = np.split(x, 2, axis=0)
print(x1, x2)

# divisão do array por colunas 2 x 2
x3, x4 = np.split(x, 2, axis=1)
print(x3, '\n',x4)

x = [[ 1  2  3 99]
 [ 3  2  1  3]]
[[ 1  2  3 99]] [[3 2 1 3]]
[[1 2]
 [3 2]] 
 [[ 3 99]
 [ 1  3]]


In [32]:
help(np.split)

Help on _ArrayFunctionDispatcher in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arra

## Universal functions 

##################################################################################

The following table lists the **arithmetic operators** implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

In [35]:
# Basic operations (+, -, *, /, %)
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9], [2, 3, -2]])

# Add two array
add = np.add(x, y)
print(add)

# Subtract two array
sub = np.subtract(x, y)
print(sub)

# Multiply two array
mul = np.multiply(x, y)
print(mul)

# Divide x, y
div = np.divide(x,y)
print(div)

# Calculated the remainder of x and y
rem = np.remainder(x, y)
print(rem)

[[ 2  6 12]
 [ 4  6  2]]
[[ 0 -2 -6]
 [ 0  0  6]]
[[ 1  8 27]
 [ 4  9 -8]]
[[ 1.          0.5         0.33333333]
 [ 1.          1.         -2.        ]]
[[0 2 3]
 [0 0 0]]


In [36]:
# multiplicação elemento a elemento, igual à função multiply
x * y

array([[ 1,  8, 27],
       [ 4,  9, -8]])

In [37]:
# Elementwise product of matrices (2-dim arrays) - confirmar

A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)

np.multiply(A, B)

[[2 0]
 [0 4]]


array([[2, 0],
       [0, 4]])

### Trigonometric function, exponentials, log

In [38]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [39]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [40]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## Sorting arrays

In [41]:
# To return a sorted version of the array without modifying the input, you can use 'np.sort':
x = np.array([2, 1, 4, 3, 5])

np.sort(x)

array([1, 2, 3, 4, 5])

In [47]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second,

In [42]:
# A related function is argsort, which instead returns the indices of the sorted elements:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [44]:
rand = np.random.RandomState(42)

# números aleatórios de 0 a 10, com 4 linhas e 6 colunas 
X = rand.randint(0, 10, (4, 6))

print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [48]:
# sort each column of X (axis=0)
np.sort(X, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [49]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second,

In [46]:
# sort each row of X (axis=1)
np.sort(X, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])